version: "3.8"

networks:
    localdev:
        name: localdev2

services:
    web:
        build: .
        restart: always
        ports:
            - "8001:80"
        depends_on:
            - mysql-db
        networks:
            - localdev2
    mysql-db:
        image: mysql
        container_name: mysql-db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: "{/nXeALX+sR88cA@GW:cKEB/Z*?HcZCt"
        ports:
            - "3307:3306"
        networks:
            - localdev2